/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../../../../../../Users/admin/AppData/Local/Android/Sdk/ndk-bundle/sysroot/usr/include/jni.h"
/* Header for class com_baitu_jnitest_UnInstallListen */

#ifndef _Included_com_baitu_jnitest_UnInstallListen
#define _Included_com_baitu_jnitest_UnInstallListen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baitu_jnitest_UnInstallListen
 * Method:    register
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_baitu_jnitest_UnInstallListen_register
  (JNIEnv *, jclass, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
